/*
mod_S5_tabshow
Author: Shape 5 - Professional Template Community
Available for download at www.shape5.com
Copyright Shape 5 LLC
*/

function s5_tabshowhover_copy1() {
if (s5_ts_ifvisible2 >= 1) {
var s5s_active1_copy = document.getElementById("copy_thumb0");}
if (s5_ts_ifvisible2 >= 2) {
var s5s_active2_copy = document.getElementById("copy_thumb1");}
if (s5_ts_ifvisible2 >= 3) {
var s5s_active3_copy = document.getElementById("copy_thumb2");}	
if (s5_ts_ifvisible2 >= 4) {
var s5s_active4_copy = document.getElementById("copy_thumb3");}
if (s5_ts_ifvisible2 >= 5) {
var s5s_active5_copy = document.getElementById("copy_thumb4");}
if (s5_ts_ifvisible2 >= 6) {
var s5s_active6_copy = document.getElementById("copy_thumb5");}
if (s5_ts_ifvisible2 >= 7) {
var s5s_active7_copy = document.getElementById("copy_thumb6");}
if (s5_ts_ifvisible2 >= 8) {
var s5s_active8_copy = document.getElementById("copy_thumb7");}
if (s5_ts_ifvisible2 >= 9) {
var s5s_active9_copy = document.getElementById("copy_thumb8");}
if (s5_ts_ifvisible2 >= 10) {
var s5s_active1_copy0 = document.getElementById("copy_thumb9");}
if (s5_ts_ifvisible2 >= 1) {
s5s_active1_copy.className="active_ts_c";}
if (s5_ts_ifvisible2 >= 2) {
s5s_active2_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 3) {
s5s_active3_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 4) {
s5s_active4_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 5) {
s5s_active5_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 6) {
s5s_active6_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 7) {
s5s_active7_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 8) {
s5s_active8_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 9) {
s5s_active9_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 10) {
s5s_active1_copy0.className="nonactive_ts_c";}
}

function s5_tabshowhover_copy2() {
if (s5_ts_ifvisible2 >= 1) {	
var s5s_active1_copy = document.getElementById("copy_thumb0");}
if (s5_ts_ifvisible2 >= 2) {
var s5s_active2_copy = document.getElementById("copy_thumb1");}
if (s5_ts_ifvisible2 >= 3) {
var s5s_active3_copy = document.getElementById("copy_thumb2");}
if (s5_ts_ifvisible2 >= 4) {
var s5s_active4_copy = document.getElementById("copy_thumb3");}
if (s5_ts_ifvisible2 >= 5) {
var s5s_active5_copy = document.getElementById("copy_thumb4");}
if (s5_ts_ifvisible2 >= 6) {
var s5s_active6_copy = document.getElementById("copy_thumb5");}
if (s5_ts_ifvisible2 >= 7) {
var s5s_active7_copy = document.getElementById("copy_thumb6");}
if (s5_ts_ifvisible2 >= 8) {
var s5s_active8_copy = document.getElementById("copy_thumb7");}
if (s5_ts_ifvisible2 >= 9) {
var s5s_active9_copy = document.getElementById("copy_thumb8");}
if (s5_ts_ifvisible2 >= 10) {
var s5s_active1_copy0 = document.getElementById("copy_thumb9");}
if (s5_ts_ifvisible2 >= 1) {	
s5s_active1_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 2) {	
s5s_active2_copy.className="active_ts_c";}
if (s5_ts_ifvisible2 >= 3) {	
s5s_active3_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 4) {	
s5s_active4_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 5) {	
s5s_active5_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 6) {	
s5s_active6_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 7) {	
s5s_active7_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 8) {	
s5s_active8_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 9) {	
s5s_active9_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 10) {	
s5s_active1_copy0.className="nonactive_ts_c";}
}

function s5_tabshowhover_copy3() {
if (s5_ts_ifvisible2 >= 1) {	
var s5s_active1_copy = document.getElementById("copy_thumb0");}
if (s5_ts_ifvisible2 >= 2) {	
var s5s_active2_copy = document.getElementById("copy_thumb1");}
if (s5_ts_ifvisible2 >= 3) {	
var s5s_active3_copy = document.getElementById("copy_thumb2");}
if (s5_ts_ifvisible2 >= 4) {	
var s5s_active4_copy = document.getElementById("copy_thumb3");}
if (s5_ts_ifvisible2 >= 5) {	
var s5s_active5_copy = document.getElementById("copy_thumb4");}
if (s5_ts_ifvisible2 >= 6) {	
var s5s_active6_copy = document.getElementById("copy_thumb5");}
if (s5_ts_ifvisible2 >= 7) {	
var s5s_active7_copy = document.getElementById("copy_thumb6");}
if (s5_ts_ifvisible2 >= 8) {	
var s5s_active8_copy = document.getElementById("copy_thumb7");}
if (s5_ts_ifvisible2 >= 9) {	
var s5s_active9_copy = document.getElementById("copy_thumb8");}
if (s5_ts_ifvisible2 >= 10) {	
var s5s_active1_copy0 = document.getElementById("copy_thumb9");}
if (s5_ts_ifvisible2 >= 1) {	
s5s_active1_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 2) {	
s5s_active2_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 3) {	
s5s_active3_copy.className="active_ts_c";}
if (s5_ts_ifvisible2 >= 4) {	
s5s_active4_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 5) {	
s5s_active5_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 6) {	
s5s_active6_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 7) {	
s5s_active7_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 8) {	
s5s_active8_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 9) {	
s5s_active9_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 10) {	
s5s_active1_copy0.className="nonactive_ts_c";}
}


function s5_tabshowhover_copy4() {
if (s5_ts_ifvisible2 >= 1) {	
var s5s_active1_copy = document.getElementById("copy_thumb0");}
if (s5_ts_ifvisible2 >= 2) {	
var s5s_active2_copy = document.getElementById("copy_thumb1");}
if (s5_ts_ifvisible2 >= 3) {	
var s5s_active3_copy = document.getElementById("copy_thumb2");}
if (s5_ts_ifvisible2 >= 4) {	
var s5s_active4_copy = document.getElementById("copy_thumb3");}
if (s5_ts_ifvisible2 >= 5) {	
var s5s_active5_copy = document.getElementById("copy_thumb4");}
if (s5_ts_ifvisible2 >= 6) {	
var s5s_active6_copy = document.getElementById("copy_thumb5");}
if (s5_ts_ifvisible2 >= 7) {	
var s5s_active7_copy = document.getElementById("copy_thumb6");}
if (s5_ts_ifvisible2 >= 8) {	
var s5s_active8_copy = document.getElementById("copy_thumb7");}
if (s5_ts_ifvisible2 >= 9) {	
var s5s_active9_copy = document.getElementById("copy_thumb8");}
if (s5_ts_ifvisible2 >= 10) {	
var s5s_active1_copy0 = document.getElementById("copy_thumb9");}
if (s5_ts_ifvisible2 >= 1) {	
s5s_active1_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 2) {	
s5s_active2_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 3) {	
s5s_active3_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 4) {	
s5s_active4_copy.className="active_ts_c";}
if (s5_ts_ifvisible2 >= 5) {	
s5s_active5_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 6) {	
s5s_active6_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 7) {	
s5s_active7_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 8) {	
s5s_active8_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 9) {	
s5s_active9_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 10) {	
s5s_active1_copy0.className="nonactive_ts_c";}
}

function s5_tabshowhover_copy5() {
if (s5_ts_ifvisible2 >= 1) {	
var s5s_active1_copy = document.getElementById("copy_thumb0");}
if (s5_ts_ifvisible2 >= 2) {	
var s5s_active2_copy = document.getElementById("copy_thumb1");}
if (s5_ts_ifvisible2 >= 3) {	
var s5s_active3_copy = document.getElementById("copy_thumb2");}
if (s5_ts_ifvisible2 >= 4) {	
var s5s_active4_copy = document.getElementById("copy_thumb3");}
if (s5_ts_ifvisible2 >= 5) {	
var s5s_active5_copy = document.getElementById("copy_thumb4");}
if (s5_ts_ifvisible2 >= 6) {	
var s5s_active6_copy = document.getElementById("copy_thumb5");}
if (s5_ts_ifvisible2 >= 7) {	
var s5s_active7_copy = document.getElementById("copy_thumb6");}
if (s5_ts_ifvisible2 >= 8) {	
var s5s_active8_copy = document.getElementById("copy_thumb7");}
if (s5_ts_ifvisible2 >= 9) {	
var s5s_active9_copy = document.getElementById("copy_thumb8");}
if (s5_ts_ifvisible2 >= 10) {	
var s5s_active1_copy0 = document.getElementById("copy_thumb9");}
if (s5_ts_ifvisible2 >= 1) {	
s5s_active1_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 2) {	
s5s_active2_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 3) {	
s5s_active3_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 4) {	
s5s_active4_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 5) {	
s5s_active5_copy.className="active_ts_c";}
if (s5_ts_ifvisible2 >= 6) {	
s5s_active6_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 7) {	
s5s_active7_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 8) {	
s5s_active8_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 9) {	
s5s_active9_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 10) {	
s5s_active1_copy0.className="nonactive_ts_c";}
}

function s5_tabshowhover_copy6() {
if (s5_ts_ifvisible2 >= 1) {	
var s5s_active1_copy = document.getElementById("copy_thumb0");}
if (s5_ts_ifvisible2 >= 2) {	
var s5s_active2_copy = document.getElementById("copy_thumb1");}
if (s5_ts_ifvisible2 >= 3) {	
var s5s_active3_copy = document.getElementById("copy_thumb2");}
if (s5_ts_ifvisible2 >= 4) {	
var s5s_active4_copy = document.getElementById("copy_thumb3");}
if (s5_ts_ifvisible2 >= 5) {	
var s5s_active5_copy = document.getElementById("copy_thumb4");}
if (s5_ts_ifvisible2 >= 6) {	
var s5s_active6_copy = document.getElementById("copy_thumb5");}
if (s5_ts_ifvisible2 >= 7) {	
var s5s_active7_copy = document.getElementById("copy_thumb6");}
if (s5_ts_ifvisible2 >= 8) {	
var s5s_active8_copy = document.getElementById("copy_thumb7");}
if (s5_ts_ifvisible2 >= 9) {	
var s5s_active9_copy = document.getElementById("copy_thumb8");}
if (s5_ts_ifvisible2 >= 10) {	
var s5s_active1_copy0 = document.getElementById("copy_thumb9");}
if (s5_ts_ifvisible2 >= 1) {	
s5s_active1_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 2) {	
s5s_active2_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 3) {	
s5s_active3_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 4) {	
s5s_active4_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 5) {	
s5s_active5_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 6) {	
s5s_active6_copy.className="active_ts_c";}
if (s5_ts_ifvisible2 >= 7) {	
s5s_active7_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 8) {	
s5s_active8_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 9) {	
s5s_active9_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 10) {	
s5s_active1_copy0.className="nonactive_ts_c";}
}

function s5_tabshowhover_copy7() {
if (s5_ts_ifvisible2 >= 1) {	
var s5s_active1_copy = document.getElementById("copy_thumb0");}
if (s5_ts_ifvisible2 >= 2) {	
var s5s_active2_copy = document.getElementById("copy_thumb1");}
if (s5_ts_ifvisible2 >= 3) {	
var s5s_active3_copy = document.getElementById("copy_thumb2");}
if (s5_ts_ifvisible2 >= 4) {	
var s5s_active4_copy = document.getElementById("copy_thumb3");}
if (s5_ts_ifvisible2 >= 5) {	
var s5s_active5_copy = document.getElementById("copy_thumb4");}
if (s5_ts_ifvisible2 >= 6) {	
var s5s_active6_copy = document.getElementById("copy_thumb5");}
if (s5_ts_ifvisible2 >= 7) {	
var s5s_active7_copy = document.getElementById("copy_thumb6");}
if (s5_ts_ifvisible2 >= 8) {	
var s5s_active8_copy = document.getElementById("copy_thumb7");}
if (s5_ts_ifvisible2 >= 9) {	
var s5s_active9_copy = document.getElementById("copy_thumb8");}
if (s5_ts_ifvisible2 >= 10) {	
var s5s_active1_copy0 = document.getElementById("copy_thumb9");}
if (s5_ts_ifvisible2 >= 1) {	
s5s_active1_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 2) {	
s5s_active2_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 3) {	
s5s_active3_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 4) {	
s5s_active4_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 5) {	
s5s_active5_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 6) {	
s5s_active6_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 7) {	
s5s_active7_copy.className="active_ts_c";}
if (s5_ts_ifvisible2 >= 8) {	
s5s_active8_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 9) {	
s5s_active9_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 10) {	
s5s_active1_copy0.className="nonactive_ts_c";}
}

function s5_tabshowhover_copy8() {
if (s5_ts_ifvisible2 >= 1) {	
var s5s_active1_copy = document.getElementById("copy_thumb0");}
if (s5_ts_ifvisible2 >= 2) {	
var s5s_active2_copy = document.getElementById("copy_thumb1");}
if (s5_ts_ifvisible2 >= 3) {	
var s5s_active3_copy = document.getElementById("copy_thumb2");}
if (s5_ts_ifvisible2 >= 4) {	
var s5s_active4_copy = document.getElementById("copy_thumb3");}
if (s5_ts_ifvisible2 >= 5) {	
var s5s_active5_copy = document.getElementById("copy_thumb4");}
if (s5_ts_ifvisible2 >= 6) {	
var s5s_active6_copy = document.getElementById("copy_thumb5");}
if (s5_ts_ifvisible2 >= 7) {	
var s5s_active7_copy = document.getElementById("copy_thumb6");}
if (s5_ts_ifvisible2 >= 8) {	
var s5s_active8_copy = document.getElementById("copy_thumb7");}
if (s5_ts_ifvisible2 >= 9) {	
var s5s_active9_copy = document.getElementById("copy_thumb8");}
if (s5_ts_ifvisible2 >= 10) {	
var s5s_active1_copy0 = document.getElementById("copy_thumb9");}
if (s5_ts_ifvisible2 >= 1) {	
s5s_active1_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 2) {	
s5s_active2_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 3) {	
s5s_active3_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 4) {	
s5s_active4_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 5) {	
s5s_active5_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 6) {	
s5s_active6_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 7) {	
s5s_active7_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 8) {	
s5s_active8_copy.className="active_ts_c";}
if (s5_ts_ifvisible2 >= 9) {	
s5s_active9_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 10) {	
s5s_active1_copy0.className="nonactive_ts_c";}
}

function s5_tabshowhover_copy9() {
if (s5_ts_ifvisible2 >= 1) {	
var s5s_active1_copy = document.getElementById("copy_thumb0");}
if (s5_ts_ifvisible2 >= 2) {	
var s5s_active2_copy = document.getElementById("copy_thumb1");}
if (s5_ts_ifvisible2 >= 3) {	
var s5s_active3_copy = document.getElementById("copy_thumb2");}
if (s5_ts_ifvisible2 >= 4) {	
var s5s_active4_copy = document.getElementById("copy_thumb3");}
if (s5_ts_ifvisible2 >= 5) {	
var s5s_active5_copy = document.getElementById("copy_thumb4");}
if (s5_ts_ifvisible2 >= 6) {	
var s5s_active6_copy = document.getElementById("copy_thumb5");}
if (s5_ts_ifvisible2 >= 7) {	
var s5s_active7_copy = document.getElementById("copy_thumb6");}
if (s5_ts_ifvisible2 >= 8) {	
var s5s_active8_copy = document.getElementById("copy_thumb7");}
if (s5_ts_ifvisible2 >= 9) {	
var s5s_active9_copy = document.getElementById("copy_thumb8");}
if (s5_ts_ifvisible2 >= 10) {	
var s5s_active1_copy0 = document.getElementById("copy_thumb9");}
if (s5_ts_ifvisible2 >= 1) {	
s5s_active1_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 2) {	
s5s_active2_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 3) {	
s5s_active3_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 4) {	
s5s_active4_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 5) {	
s5s_active5_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 6) {	
s5s_active6_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 7) {	
s5s_active7_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 8) {	
s5s_active8_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 9) {	
s5s_active9_copy.className="active_ts_c";}
if (s5_ts_ifvisible2 >= 10) {	
s5s_active1_copy0.className="nonactive_ts_c";}
}

function s5_tabshowhover_copy10() {
if (s5_ts_ifvisible2 >= 1) {	
var s5s_active1_copy = document.getElementById("copy_thumb0");}
if (s5_ts_ifvisible2 >= 2) {	
var s5s_active2_copy = document.getElementById("copy_thumb1");}
if (s5_ts_ifvisible2 >= 3) {	
var s5s_active3_copy = document.getElementById("copy_thumb2");}
if (s5_ts_ifvisible2 >= 4) {	
var s5s_active4_copy = document.getElementById("copy_thumb3");}
if (s5_ts_ifvisible2 >= 5) {	
var s5s_active5_copy = document.getElementById("copy_thumb4");}
if (s5_ts_ifvisible2 >= 6) {	
var s5s_active6_copy = document.getElementById("copy_thumb5");}
if (s5_ts_ifvisible2 >= 7) {	
var s5s_active7_copy = document.getElementById("copy_thumb6");}
if (s5_ts_ifvisible2 >= 8) {	
var s5s_active8_copy = document.getElementById("copy_thumb7");}
if (s5_ts_ifvisible2 >= 9) {	
var s5s_active9_copy = document.getElementById("copy_thumb8");}
if (s5_ts_ifvisible2 >= 10) {	
var s5s_active1_copy0 = document.getElementById("copy_thumb9");}
if (s5_ts_ifvisible2 >= 1) {	
s5s_active1_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 2) {	
s5s_active2_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 3) {	
s5s_active3_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 4) {	
s5s_active4_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 5) {	
s5s_active5_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 6) {	
s5s_active6_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 7) {	
s5s_active7_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 8) {	
s5s_active8_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 9) {	
s5s_active9_copy.className="nonactive_ts_c";}
if (s5_ts_ifvisible2 >= 10) {	
s5s_active1_copy0.className="active_ts_c";}
}