#<?php die('Direct Access To Log Files Not Permitted'); ?>
#Version: 1.0
#Date: 2011-09-22 11:32:18
#Fields: date	time	level	c-ip	status	comment
#Software: Joomla! 1.5.23 Stable [ senu takaa ama baji ] 04-March-2011 18:00 GMT
2011-09-22	11:32:18	1	78.161.33.100	SOME ERROR:	SELECT
					STANDART_ID,
					SEVIYE_ADI,
					STANDART_ADI,
					KURULUS_ADI,
					EVRAK_ID 
			FROM M_MESLEK_STANDARTLARI USING (STANDART_ID)
			JOIN PM_MESLEK_STANDART_DURUM USING (MESLEK_STANDART_DURUM_ID)
			JOIN PM_SEVIYE USING (SEVIYE_ID) 
      		JOIN M_MESLEK_STAN_EVRAK USING(STANDART_ID)
			LEFT JOIN ".DB_PREFIX.".EVRAK USING (EVRAK_ID) 
			JOIN M_KURULUS USING (USER_ID) 
		WHERE ( STANDART_ID NOT IN (SELECT STANDART_ID FROM M_TASLAK_MESLEK)
          AND M_KURULUS.MS_LISTE_ONAY = 1 
          AND MESLEK_STANDART_DURUM_ID != -3)	
		
		
		 
		
		
		 ORDER BY STANDART_ADI